### ISSUE TITLE
Configurable Lease times

### ISSUE THREAD

**Issue by damdo** [kkosmrli/leader-elector#2]
First of all, thank you for your work on this handy tool.
I was thinking that it would be great to have these Lease Times to be configurable via flags:

https://github.com/kkosmrli/leader-elector/blob/a441867812f73f2e4c3257d531a58a7f9799faaa/pkg/election/election.go#L48-L54

so then we would be able to set them from the Deployment.
Do you think this could be valuable? I could try this in a Pull Request if you are interested.

**Comment by kkosmrli** [comment]
Sure go for it, this could definitely be useful. I'm thankfull for all contributions.
